name: Git Command

on:
  push:
    branches:
      - '*'
jobs:
  git_command:
    runs-on: ubuntu-latest
    permissions:
      : write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: git setting
        run: |
          git config --local user.email "takuya@netlab.jp"
          git config --local user.name "${GITHUB_ACTOR}"
      - name: Commit files
        run: |
          echo test > test.txt
          git add .
          git commit -m "Add test.txt"
          git pull
          git push origin "${GITHUB_REF_NAME}"
      - name: Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gem-${{ hashFiles('**/test.txt') }}
          path: ./
